### PR TITLE
Declare python-environ missing dependency

### PR DESCRIPTION
**Pull request by Kraymer**

### CODE REVIEW

**Comment by nandoks** [comment]
Requirements.txt already has django-environ on it, can you explain why it needs both? or should it have one instead of the other?

**Comment by Kraymer** [comment]
I just noticed this check on the PR :  
Selection_999(1737)

do you know if this check was failing when the credentials were stored in the .py files ?

**Comment by nandoks** [comment]
I didn't noticed it on github, but looking on gitguardian dashboard it caught the presence of sensitive information and raised a redflag.

**Comment by Kraymer** [comment]
> Requirements.txt already has django-environ on it, can you explain why it needs both? or should it have one instead of the other?

My bad, there definitely should not be both of them.

The problem I have is this : 

~~~
❯ /home/flap/Dev/TeacherPlan/.venv/py3/bin/pytest   # current master config, error when running tests
Traceback (most recent call last):
  File "/home/flap/Dev/TeacherPlan/.venv/py3/bin/pytest", line 8, in <module>
    sys.exit(console_main())
  File "/home/flap/Dev/TeacherPlan/.venv/py3/lib/python3.6/site-packages/_pytest/config/__init__.py", line 185, in console_main
    code = main()
  File "/home/flap/Dev/TeacherPlan/.venv/py3/lib/python3.6/site-packages/_pytest/config/__init__.py", line 143, in main
    config = _prepareconfig(args, plugins)
  File "/home/flap/Dev/TeacherPlan/.venv/py3/lib/python3.6/site-packages/_pytest/config/__init__.py", line 319, in _prepareconfig
    pluginmanager=pluginmanager, args=args
  File "/home/flap/Dev/TeacherPlan/.venv/py3/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/flap/Dev/TeacherPlan/.venv/py3/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/flap/Dev/TeacherPlan/.venv/py3/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/home/flap/Dev/TeacherPlan/.venv/py3/lib/python3.6/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/home/flap/Dev/TeacherPlan/.venv/py3/lib/python3.6/site-packages/_pytest/helpconfig.py", line 100, in pytest_cmdline_parse
    config: Config = outcome.get_result()
  File "/home/flap/Dev/TeacherPlan/.venv/py3/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/flap/Dev/TeacherPlan/.venv/py3/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/flap/Dev/TeacherPlan/.venv/py3/lib/python3.6/site-packages/_pytest/config/__init__.py", line 1003, in pytest_cmdline_parse
    self.parse(args)
  File "/home/flap/Dev/TeacherPlan/.venv/py3/lib/python3.6/site-packages/_pytest/config/__init__.py", line 1283, in parse
    self._preparse(args, addopts=addopts)
  File "/home/flap/Dev/TeacherPlan/.venv/py3/lib/python3.6/site-packages/_pytest/config/__init__.py", line 1192, in _preparse
    early_config=self, args=args, parser=self._parser
  File "/home/flap/Dev/TeacherPlan/.venv/py3/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/flap/Dev/TeacherPlan/.venv/py3/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/flap/Dev/TeacherPlan/.venv/py3/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/home/flap/Dev/TeacherPlan/.venv/py3/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/home/flap/Dev/TeacherPlan/.venv/py3/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/flap/Dev/TeacherPlan/.venv/py3/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/flap/Dev/TeacherPlan/.venv/py3/lib/python3.6/site-packages/pytest_django/plugin.py", line 347, in pytest_load_initial_conftests
    dj_settings.DATABASES
  File "/home/flap/Dev/TeacherPlan/.venv/py3/lib/python3.6/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/home/flap/Dev/TeacherPlan/.venv/py3/lib/python3.6/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/flap/Dev/TeacherPlan/.venv/py3/lib/python3.6/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/flap/Dev/TeacherPlan/TeacherPlan/settings/__init__.py", line 1, in <module>
    from .dev import *
  File "/home/flap/Dev/TeacherPlan/TeacherPlan/settings/dev.py", line 4, in <module>
    env = environ.Env()
AttributeError: module 'environ' has no attribute 'Env'

❯ pip3 install python-environ
❯ /home/flap/Dev/TeacherPlan/.venv/py3/bin/pytest  # tests executed
[...]
-- Docs: https://docs.pytest.org/en/stable/warnings.html
====================================================================================================== short test summary info =======================================================================================================
FAILED lesson/tests/test_lesson.py::TestLessonCase::test_no_creation_overlap_student - django.db.utils.IntegrityError: null value in column "student_id" violates not-null constraint
FAILED lesson/tests/test_lesson.py::TestLessonCase::test_no_creation_overlap_teacher - django.db.utils.IntegrityError: null value in column "student_id" violates not-null constraint
==================================================================================================== 2 failed, 1 warning in 2.83s ====================================================================================================
~~~

Can you reproduce it ?

**Comment by nandoks** [comment]
I did not get the same error on env variables when running the tests, Django-environ works for my .env file and I didn't need to install python-environ. 
Otherwise the tests failed and i got the same errors
Did you check if you had django-environ installed before tried running the tests?

**Comment by Kraymer** [comment]
I can't reproduce on my system anymore :man_shrugging:
Later on, once you'll have some units tests written, you may want to look at tools like [tox](https://pypi.org/project/tox/) that take care of running the tests in isolated environments.

**Pull request closed without merging**
